package com.example.rag;

import com.example.rag.service.DocumentService;
import com.example.rag.service.RagService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Scanner;

/**
 * Main application class for the RAG (Retrieval-Augmented Generation) system.
 * This application demonstrates how to use LangChain4J with Milvus vector database
 * to build a question-answering system over documents.
 */
public class RagApplication {
    private static final Logger logger = LoggerFactory.getLogger(RagApplication.class);

    public static void main(String[] args) {
        logger.info("Starting RAG Application with LangChain4J and Milvus");

        try {
            // Initialize services
            DocumentService documentService = new DocumentService();
            RagService ragService = new RagService(documentService);

            // Initialize the vector database
            documentService.initialize();

            // Load sample documents if the collection is empty
            if (documentService.getDocumentCount() == 0) {
                logger.info("Loading sample documents...");
                loadSampleDocuments(documentService);
            }

            // Start interactive session
            startInteractiveSession(ragService);

        } catch (Exception e) {
            logger.error("Error starting RAG application", e);
            System.exit(1);
        }
    }

    private static void loadSampleDocuments(DocumentService documentService) {
        String[] sampleDocs = {
            "Java is a high-level, class-based, object-oriented programming language. It was originally developed by James Gosling at Sun Microsystems and released in 1995.",
            "LangChain4J is a Java library that makes it easy to integrate Large Language Models (LLMs) into Java applications. It provides abstractions for working with various LLM providers.",
            "Milvus is an open-source vector database built for scalable similarity search and AI applications. It can store, index, and manage massive embedding vectors generated by deep neural networks.",
            "Retrieval-Augmented Generation (RAG) is a technique that combines information retrieval with text generation. It retrieves relevant documents and uses them to generate more accurate and contextual responses.",
            "Docker is a platform that uses containerization technology to package applications and their dependencies into lightweight, portable containers that can run consistently across different environments."
        };

        for (int i = 0; i < sampleDocs.length; i++) {
            documentService.addDocument("doc_" + (i + 1), sampleDocs[i]);
        }

        logger.info("Loaded {} sample documents", sampleDocs.length);
    }

    private static void startInteractiveSession(RagService ragService) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("\n=== RAG Question-Answering System ===");
        System.out.println("Ask questions about the loaded documents. Type 'exit' to quit.\n");

        while (true) {
            System.out.print("Question: ");
            String question = scanner.nextLine().trim();

            if ("exit".equalsIgnoreCase(question)) {
                break;
            }

            if (question.isEmpty()) {
                continue;
            }

            try {
                String answer = ragService.answer(question);
                System.out.println("Answer: " + answer + "\n");
            } catch (Exception e) {
                logger.error("Error processing question: " + question, e);
                System.out.println("Sorry, I encountered an error processing your question.\n");
            }
        }

        scanner.close();
        System.out.println("Goodbye!");
    }
}
